#!/bin/bash

install_script="$1"
installerName="$2"
tbz="$3" # the tar.bz2 of the php application
apacheRestarter="$4" # the setuid binary to restart Apache
version="$5"

rm -rf "$installerName"

/usr/local/bin/platypus \
    -a "Web iPhoto Access installer" \
    -o "Text Window" \
    -i "build_resources/installer.icns" \
    -u "Alexandre Feblot" \
    -f "$(pwd)/$tbz" \
    -f "$(pwd)/$apacheRestarter" \
    -V "$version" \
    -A \
    -R \
    -F \
    -b "#ffffff" -g "#000000" \
    -c "$install_script" \
    "$installerName"
