<?php

/*
Copyright Alexandre Feblot, 2005-2006
http://globs.org

This software is a computer program whose purpose is to let people share
their iPhoto Library on the web, and let their users easily download a
bundle of pictures.

This software is governed by the CeCILL  license under French law and
abiding by the rules of distribution of free software.  You can  use, 
modify and/ or redistribute the software under the terms of the CeCILL
license as circulated by CEA, CNRS and INRIA at the following URL
"http://www.cecill.info". 

As a counterpart to the access to the source code and  rights to copy,
modify and redistribute granted by the license, users are provided only
with a limited warranty  and the software's author,  the holder of the
economic rights,  and the successive licensors  have only  limited
liability. 

In this respect, the user's attention is drawn to the risks associated
with loading,  using,  modifying and/or developing or reproducing the
software by the user in light of its specific status of free software,
that may mean  that it is complicated to manipulate,  and  that  also
therefore means  that it is reserved for developers  and  experienced
professionals having in-depth computer knowledge. Users are therefore
encouraged to load and test the software's suitability as regards their
requirements in conditions enabling the security of their systems and/or 
data to be ensured and,  more generally, to use and operate it in the 
same conditions as regards security. 

The fact that you are presently reading this means that you have had
knowledge of the CeCILL license and that you accept its terms.
*/

require_once('zipper.php');
define('NEWLINE', chr(10));

//=============================================================================
class PhotosZip extends zipper {

    var $photoIndexToAdd = 0;
    var $index = NULL; // text index file content
    var $import = NULL; // applescript import file content
    var $downloadIds = NULL;
    var $photos = NULL;
    var $library = NULL;
    //----------------------------------------------
    function PhotosZip($name, $doStream, $doMultipart, &$downloadIds, &$photos, $library) {
        $this->downloadIds = $downloadIds;
        $this->photos = $photos;
        $this->library = $library;
        $this->zipper($name, 6, $doStream, $doMultipart);
        $importName = strftime("Web iPhoto Access Import (%d %b %Y, %H:%M:%S)");
        $this->index = '          ------ INDEX ------'.NEWLINE.NEWLINE;
        $this->import = <<<EOS
#!/bin/sh
# Generated by Web iPhoto Access to import its export into iPhoto.
# The script will import the photos in a new album, with their original captions and comments.

photoDir="$(dirname "$0")/Photos"

/usr/bin/osascript <<END_SCRIPT >& /dev/null
tell application "iPhoto"
    activate 
	new album name "$importName"
	import from "\$photoDir" to album "$importName"
	try
		repeat while importing is true
			delay 1
		end repeat
	end try

EOS;
// Don't remove the blank line just before EOS !!!
    }

    //----------------------------------------------
    function addNextPhoto() {
        if (count($this->downloadIds)==$this->photoIndexToAdd) {
            return 1.0;
        }
        $photo = $this->photos[$this->downloadIds[$this->photoIndexToAdd]];
        $this->photoIndexToAdd++;

        // Add infos to the index text file
        $this->index .= NEWLINE . NEWLINE . basename($photo['ImagePath']);
        if ($photo['Caption']) $this->index .= NEWLINE . '    '. $photo['Caption'];
        if ($photo['Comment']) $this->index .= NEWLINE . '    '. $photo['Comment'];
        $this->index .= NEWLINE . strftime("    %d %b %Y, %H:%M:%S", $photo['Timestamp']);

        $filein = getMacAliasOriginal($this->library.$photo['ImagePath'], $error);
        $fileout = basename($filein);

        if (isset($filein)) {
            if ( ! @file_exists($filein)) {
                $error = "Can't find file '$fileout' (or is it a higher directory permission issue?)";
            }
            if ( ! @is_readable($filein)) {
                $error = "File '$fileout' is not readable (permission issue)";
            }
        }
        if (isset($error)) {
            $this->index .= NEWLINE . "    *** ERROR ***: " . $error;
        } else {
            $this->addFile($filein, "Photos/$fileout", false);

            // Add infos to the iphoto import script
            $defCaption = preg_replace('/\.\w+/', '', $fileout);
            if ($photo['Comment']) $this->import .= '    set comment of photo "'.$defCaption.'" to '.applecriptUnicode($photo['Comment']).NEWLINE;
            if ($photo['Caption']) $this->import .= '    set title   of photo "'.$defCaption.'" to '.applecriptUnicode($photo['Caption']).NEWLINE;
        }

        // Return the %completed of zip creation
        return $this->photoIndexToAdd/count($this->downloadIds);
    }

    //----------------------------------------------
    function addAllPhotos() {
        $p=0;
        while($p<1) {
            $p = $this->addNextPhoto();
        }
    }

    //----------------------------------------------
    function save() {
        $this->import .= <<<EOS
    display alert "WiPhA import" message "Import completed" as informational
end tell
END_SCRIPT

EOS;
// Don't remove the blank line just before EOS!!!

        $this->addData($this->index, 'index.txt');
        $this->addData($this->import, 'import.command');
        $this->close();
    }
}

?>
