{math equation="ceil(275*p/100)" p=$percent assign="width"}
<div class="percents">{$percent}%&nbsp;complete</div><div class="blocks" style="width:{$width}px">&nbsp;</div>
{if $percent == 100 and $versionOk}
    <script type="text/javascript">
    Behaviour.addLoadEvent( function() {ldelim}window.location="{$nexturl}";{rdelim} );
    </script>
    </body>
    </html>
{/if}
{if ! $versionOk}
    <div class="warn">
    <p> This library seems to have been generated by iPhoto <strong>{$version}</strong>.
    WiPhA only supports iPhoto 4 and greater.</p>
    </div>
{/if}
{php}
    flush();
{/php}
